server:
  port: 8081
  servlet:
    context-path: /auth-service

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authDB
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: "oZNYys2LweTrJc3DqEp+zFOz8LbqbqTNzOEAE5eHIs65gnJEN3rlAGpzk2P1hYFP"
  valid-duration: 3600 # 1 hour
  refresh-duration: 36000 # 10 hours