server:
  port: 8080

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: http://auth-service
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2

        - id: user-service
          uri: http://user-service
          predicates:
            - Path=${app.api-prefix}/users/**
          filters:
            - StripPrefix=2

        - id: notification-service
          uri: http://notification-service
          predicates:
            - Path=${app.api-prefix}/notifications/**
          filters:
            - StripPrefix=2

        - id: posts-service
          uri: http://posts-service
          predicates:
            - Path=${app.api-prefix}/feed/**
          filters:
            - StripPrefix=2

data:
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Địa chỉ của Eureka Server
  instance:
    preferIpAddress: true