server:
  port: 8080
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/${app.api-prefix}/auth/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
            
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/${app.api-prefix}/users/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackUri: forward:/fallback
                
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/${app.api-prefix}/notifications/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: notificationCircuitBreaker
                fallbackUri: forward:/fallback
  
  redis:
    host: localhost
    port: 6379
    
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        
  ratelimiter:
    configs:
      default:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 1s
      auth:
        limitForPeriod: 20
        limitRefreshPeriod: 1s
        timeoutDuration: 1s
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
jwt:
  public-key-location: classpath:public.pem
    
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    reactor.netty: INFO
    
app:
  api-prefix: api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
