server:
  port: 8083
  servlet:
    context-path: /feed

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/postDB?authSource=admin
      auto-index-creation: true

app:
  user-service:
    url: http://user-service:8082
  auth-service:
    url: http://auth-service:8081

jwt:
  signerKey: "oZNYys2LweTrJc3DqEp+zFOz8LbqbqTNzOEAE5eHIs65gnJEN3rlAGpzk2P1hYFP"
  valid-duration: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic