server:
  port: 8083
  servlet:
    context-path: /feed

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://root:rootpassword@localhost:27017/postDB?authSource=admin
      auto-index-creation: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

# MongoDB initialization script path
mongodb:
  init-script: classpath:schema.js
  
# Custom application script execution
app:
  mongo:
    init-enabled: true
    init-script: classpath:schema.js
  auth-service:
    url: http://localhost:8081
  user-service:
    url: http://localhost:8082
  notification-service:
    url: http://localhost:8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8081
        jwk-set-uri: http://localhost:8081/.well-known/jwks.json

logging:
  level:
    org.springframework.data.mongodb: INFO
    com.socialmedia.postservice: DEBUG
