server:
  port: 8083
  servlet:
    context-path: /feed

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://root:rootpassword@localhost:27017/postDB?authSource=admin
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

app:
  auth-service:
    url: http://localhost:8081
  user-service:
    url: http://localhost:8082
  notification-service:
    url: http://localhost:8084
  data:
    # Đặt giá trị này là 'true' để kích hoạt khởi tạo dữ liệu khi ứng dụng chạy với profile 'dev' hoặc 'test'.
    initialize: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8081
        jwk-set-uri: http://localhost:8081/.well-known/jwks.json

logging:
  level:
    org.springframework.data.mongodb: INFO
    com.socialmedia.postservice: DEBUG