server:
  port: 8082

spring:
  application:
    name: user-service
  neo4j:
    uri: bolt://localhost:7474
    authentication:
      username: neo4j
      password: password
  data:
    neo4j:
      database: neo4j
      repositories:
        type: auto
      
# Custom script execution for Neo4j
app:
  neo4j:
    init-script: classpath:schema.cypher
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8081
        jwk-set-uri: http://localhost:8081/.well-known/jwks.json
        
logging:
  level:
    org.springframework.data.neo4j: INFO
    com.socialmedia.userservice: DEBUG
