server:
  port: 8082

spring:
  application:
    name: user-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true