server:
  port: 8080

app:
  api-prefix: api/v1

spring:
  application:
    name: api-gateway-service
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      # Disable rate limiting temporarily
      # default-filters:
      #   - name: RequestRateLimiter
      #     args:
      #       redis-rate-limiter.replenishRate: 10
      #       redis-rate-limiter.burstCapacity: 20
      #       redis-rate-limiter.requestedTokens: 1
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/${app.api-prefix}/users/**
          filters:
            - StripPrefix=2

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/${app.api-prefix}/posts/**
          filters:
            - StripPrefix=2

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/${app.api-prefix}/search/**
          filters:
            - StripPrefix=2

    discovery:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true




