server:
    port: 8080

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/auth-service/**
          filters:
            - StripPrefix=2





